gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Jekyll Starter
description: Prototyping starter kit for Jekyll

# Name of project on Github
baseurl: /masters-of-3d

# Build settings
markdown: kramdown


# navigate to http://localhost:4000/masters-of-3d/
# Deploy with:
# jekyll build && git subtree push --prefix build origin gh-pages
